In [ ]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(100,size=(3,4,5))
print(x3)
print("x3: ",x3.ndim)
print("x3 shape: ",x3.shape)




[[[46 88 81 37 25]
  [77 72  9 20 80]
  [69 79 47 64 82]
  [99 88 49 29 19]]

 [[19 14 39 32 65]
  [ 9 57 32 31 74]
  [23 35 75 55 28]
  [34  0  0 36 53]]

 [[ 5 38 17 79  4]
  [42 58 31  1 65]
  [41 57 35 11 46]
  [82 91  0 14 99]]]
x3:  3
x3 shape:  (3, 4, 5)


In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[-1]

9

In [ ]:
x2[0,0]

3

In [ ]:
x2[2,-1]

7

In [ ]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]

array([4, 5, 6])

In [ ]:
x[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x2[:3,::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [ ]:
print(x2[0,:])

[3 5 2 4]


In [ ]:
print(x2[:,0])

[3 7 1]


In [ ]:
print(x2[0,:])
print(x2[0])

[3 5 2 4]
[3 5 2 4]


In [ ]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [ ]:
x2_sub=x2[:2,:2]
print(x2_sub)

[[3 5]
 [7 6]]


In [ ]:
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[3 5]
 [7 6]]


In [ ]:
x2_sub_copy[0,0]=888
print(x2_sub_copy)

[[888   5]
 [  7   6]]


In [ ]:
grid=np.arange(1,10).reshape((3,3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
grid=np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x=np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [ ]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [ ]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
z=[99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
grid=np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
grid=np.arange(9).reshape(3,3)
print(grid)
np.concatenate([grid,grid],axis=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
x=[4,5,6,88,88,6,5,4]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[4 5 6] [88 88] [6 5 4]


In [ ]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
